"""empty message

Revision ID: 5e9f08ce46b4
Revises: 2833a509f5b9
Create Date: 2024-02-19 23:34:15.693323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9f08ce46b4'
down_revision = '2833a509f5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('venues', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'created_date')
    op.drop_column('artists', 'created_date')
    # ### end Alembic commands ###
