"""empty message

Revision ID: a29c6597c60a
Revises: 96a29e162743
Create Date: 2024-02-12 22:25:18.383471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29c6597c60a'
down_revision = '96a29e162743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('upcoming', sa.Boolean(), nullable=True))
    op.add_column('shows', sa.Column('past', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'past')
    op.drop_column('shows', 'upcoming')
    # ### end Alembic commands ###
